//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace B1993.Web.com {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="sWebBambooSoap", Namespace="http://dreamtoday.top/")]
    public partial class sWebBamboo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LifeUserAuthenticationDy lifeUserAuthenticationDyValueField;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private LifeUserAuthentication lifeUserAuthenticationValueField;
        
        private System.Threading.SendOrPostCallback HelloWorld2OperationCompleted;
        
        private System.Threading.SendOrPostCallback search_productOperationCompleted;
        
        private System.Threading.SendOrPostCallback product_typeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getproductinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChangeProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJSconfigOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public sWebBamboo() {
            this.Url = global::B1993.Web.Properties.Settings.Default.B1993_Web_com_sWebBamboo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LifeUserAuthenticationDy LifeUserAuthenticationDyValue {
            get {
                return this.lifeUserAuthenticationDyValueField;
            }
            set {
                this.lifeUserAuthenticationDyValueField = value;
            }
        }
        
        public LifeUserAuthentication LifeUserAuthenticationValue {
            get {
                return this.lifeUserAuthenticationValueField;
            }
            set {
                this.lifeUserAuthenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event HelloWorld2CompletedEventHandler HelloWorld2Completed;
        
        /// <remarks/>
        public event search_productCompletedEventHandler search_productCompleted;
        
        /// <remarks/>
        public event product_typeCompletedEventHandler product_typeCompleted;
        
        /// <remarks/>
        public event getproductinfoCompletedEventHandler getproductinfoCompleted;
        
        /// <remarks/>
        public event getChangeProductCompletedEventHandler getChangeProductCompleted;
        
        /// <remarks/>
        public event GetJSconfigCompletedEventHandler GetJSconfigCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationDyValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/HelloWorld", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/HelloWorld2", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld2() {
            object[] results = this.Invoke("HelloWorld2", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorld2Async() {
            this.HelloWorld2Async(null);
        }
        
        /// <remarks/>
        public void HelloWorld2Async(object userState) {
            if ((this.HelloWorld2OperationCompleted == null)) {
                this.HelloWorld2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorld2OperationCompleted);
            }
            this.InvokeAsync("HelloWorld2", new object[0], this.HelloWorld2OperationCompleted, userState);
        }
        
        private void OnHelloWorld2OperationCompleted(object arg) {
            if ((this.HelloWorld2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorld2Completed(this, new HelloWorld2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/search_product", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string search_product(int stateid, string name, int PageSize, int PageNo) {
            object[] results = this.Invoke("search_product", new object[] {
                        stateid,
                        name,
                        PageSize,
                        PageNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void search_productAsync(int stateid, string name, int PageSize, int PageNo) {
            this.search_productAsync(stateid, name, PageSize, PageNo, null);
        }
        
        /// <remarks/>
        public void search_productAsync(int stateid, string name, int PageSize, int PageNo, object userState) {
            if ((this.search_productOperationCompleted == null)) {
                this.search_productOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_productOperationCompleted);
            }
            this.InvokeAsync("search_product", new object[] {
                        stateid,
                        name,
                        PageSize,
                        PageNo}, this.search_productOperationCompleted, userState);
        }
        
        private void Onsearch_productOperationCompleted(object arg) {
            if ((this.search_productCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_productCompleted(this, new search_productCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/product_type", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string product_type(int stateid, int TypeName, int PageSize, int PageNo) {
            object[] results = this.Invoke("product_type", new object[] {
                        stateid,
                        TypeName,
                        PageSize,
                        PageNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void product_typeAsync(int stateid, int TypeName, int PageSize, int PageNo) {
            this.product_typeAsync(stateid, TypeName, PageSize, PageNo, null);
        }
        
        /// <remarks/>
        public void product_typeAsync(int stateid, int TypeName, int PageSize, int PageNo, object userState) {
            if ((this.product_typeOperationCompleted == null)) {
                this.product_typeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onproduct_typeOperationCompleted);
            }
            this.InvokeAsync("product_type", new object[] {
                        stateid,
                        TypeName,
                        PageSize,
                        PageNo}, this.product_typeOperationCompleted, userState);
        }
        
        private void Onproduct_typeOperationCompleted(object arg) {
            if ((this.product_typeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.product_typeCompleted(this, new product_typeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/getproductinfo", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getproductinfo(string code) {
            object[] results = this.Invoke("getproductinfo", new object[] {
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getproductinfoAsync(string code) {
            this.getproductinfoAsync(code, null);
        }
        
        /// <remarks/>
        public void getproductinfoAsync(string code, object userState) {
            if ((this.getproductinfoOperationCompleted == null)) {
                this.getproductinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetproductinfoOperationCompleted);
            }
            this.InvokeAsync("getproductinfo", new object[] {
                        code}, this.getproductinfoOperationCompleted, userState);
        }
        
        private void OngetproductinfoOperationCompleted(object arg) {
            if ((this.getproductinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getproductinfoCompleted(this, new getproductinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/getChangeProduct", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getChangeProduct(int stateid, string TypeString) {
            object[] results = this.Invoke("getChangeProduct", new object[] {
                        stateid,
                        TypeString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getChangeProductAsync(int stateid, string TypeString) {
            this.getChangeProductAsync(stateid, TypeString, null);
        }
        
        /// <remarks/>
        public void getChangeProductAsync(int stateid, string TypeString, object userState) {
            if ((this.getChangeProductOperationCompleted == null)) {
                this.getChangeProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChangeProductOperationCompleted);
            }
            this.InvokeAsync("getChangeProduct", new object[] {
                        stateid,
                        TypeString}, this.getChangeProductOperationCompleted, userState);
        }
        
        private void OngetChangeProductOperationCompleted(object arg) {
            if ((this.getChangeProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChangeProductCompleted(this, new getChangeProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LifeUserAuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dreamtoday.top/GetJSconfig", RequestNamespace="http://dreamtoday.top/", ResponseNamespace="http://dreamtoday.top/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetJSconfig(string url) {
            object[] results = this.Invoke("GetJSconfig", new object[] {
                        url});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetJSconfigAsync(string url) {
            this.GetJSconfigAsync(url, null);
        }
        
        /// <remarks/>
        public void GetJSconfigAsync(string url, object userState) {
            if ((this.GetJSconfigOperationCompleted == null)) {
                this.GetJSconfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJSconfigOperationCompleted);
            }
            this.InvokeAsync("GetJSconfig", new object[] {
                        url}, this.GetJSconfigOperationCompleted, userState);
        }
        
        private void OnGetJSconfigOperationCompleted(object arg) {
            if ((this.GetJSconfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJSconfigCompleted(this, new GetJSconfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dreamtoday.top/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://dreamtoday.top/", IsNullable=false)]
    public partial class LifeUserAuthentication : System.Web.Services.Protocols.SoapHeader {
        
        private string userIdField;
        
        private string passWordField;
        
        private string memberIdField;
        
        private string mobilePhoneNOField;
        
        private string aPINameField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string deviceNoField;
        
        private string deviceTypeField;
        
        private string systemVersionField;
        
        private string appVersionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNO {
            get {
                return this.mobilePhoneNOField;
            }
            set {
                this.mobilePhoneNOField = value;
            }
        }
        
        /// <remarks/>
        public string APIName {
            get {
                return this.aPINameField;
            }
            set {
                this.aPINameField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceNo {
            get {
                return this.deviceNoField;
            }
            set {
                this.deviceNoField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SystemVersion {
            get {
                return this.systemVersionField;
            }
            set {
                this.systemVersionField = value;
            }
        }
        
        /// <remarks/>
        public string AppVersion {
            get {
                return this.appVersionField;
            }
            set {
                this.appVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dreamtoday.top/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://dreamtoday.top/", IsNullable=false)]
    public partial class LifeUserAuthenticationDy : System.Web.Services.Protocols.SoapHeader {
        
        private string userIdField;
        
        private string passWordField;
        
        private string areaCodeField;
        
        private string languageField;
        
        private string areaCodeSelectedField;
        
        private string memberIdField;
        
        private string mobilePhoneNOField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string deviceNoField;
        
        private string deviceTypeField;
        
        private string systemVersionField;
        
        private string appVersionField;
        
        private string areaListCodeField;
        
        private string loveMemberidField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string AreaCodeSelected {
            get {
                return this.areaCodeSelectedField;
            }
            set {
                this.areaCodeSelectedField = value;
            }
        }
        
        /// <remarks/>
        public string MemberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNO {
            get {
                return this.mobilePhoneNOField;
            }
            set {
                this.mobilePhoneNOField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceNo {
            get {
                return this.deviceNoField;
            }
            set {
                this.deviceNoField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SystemVersion {
            get {
                return this.systemVersionField;
            }
            set {
                this.systemVersionField = value;
            }
        }
        
        /// <remarks/>
        public string AppVersion {
            get {
                return this.appVersionField;
            }
            set {
                this.appVersionField = value;
            }
        }
        
        /// <remarks/>
        public string AreaListCode {
            get {
                return this.areaListCodeField;
            }
            set {
                this.areaListCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LoveMemberid {
            get {
                return this.loveMemberidField;
            }
            set {
                this.loveMemberidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void HelloWorld2CompletedEventHandler(object sender, HelloWorld2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorld2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorld2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void search_productCompletedEventHandler(object sender, search_productCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_productCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_productCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void product_typeCompletedEventHandler(object sender, product_typeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product_typeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal product_typeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void getproductinfoCompletedEventHandler(object sender, getproductinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getproductinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getproductinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void getChangeProductCompletedEventHandler(object sender, getChangeProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChangeProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChangeProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void GetJSconfigCompletedEventHandler(object sender, GetJSconfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJSconfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJSconfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591